<b>catchError</b>
The catchError operator in RxJS is used to handle errors in an observable stream. It allows you to catch an error that occurs during the emission of values and either handle it gracefully (by returning a fallback observable or some default value) or rethrow the error after logging or performing some side effects.


Checkout to the question commit of catchError branch, follow instructions written for catchError function.
<small>commit: catchError</small>